# THIS IS NOT AN ACTUAL HELM CHART!
# It's just a mechanism to have a RenovateBot update chart versions
# and let Pulumi parse dependencies and use version and repository url

apiVersion: v2
name: placholder-chart
version: 0.0.0
dependencies:
  - name: gateway-helm
    version: 1.5.0
    repository: 'oci://docker.io/envoyproxy'
  - name: minecraft
    version: 4.26.4
    repository: 'https://itzg.github.io/minecraft-server-charts/'
  - name: k8s-monitoring
    version: 3.6.0
    repository: 'https://grafana.github.io/helm-charts'
  - name: cert-manager
    version: v1.19.1
    repository: 'https://charts.jetstack.io'
  - name: alloy-crd
    version: 1.0.0
    repository: 'https://grafana.github.io/helm-charts'
